[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "deemix>=3.6.6",
    "nest-asyncio>=1.6.0",
    "python-telegram-bot==20.6",
    "requests>=2.32.5",
    "telegram>=0.0.1",
]
